/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <stdio.h>
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

FDCAN_HandleTypeDef hfdcan1;
FDCAN_HandleTypeDef hfdcan2;

UART_HandleTypeDef huart1;
DMA_HandleTypeDef hdma_usart1_tx;

/* USER CODE BEGIN PV */
static uint32_t can_tx_count = 0;
static uint32_t can_rx_count = 0;
static uint32_t can_tx_error = 0;

static uint32_t last_tx_tick = 0;
static uint32_t last_report_tick = 0;

/*
 * Independent validation of the traffic seen by generator FDCAN2.
 *
 * This is the reference receiver for the BusAnalyzerII acquisition
 * investigation.  The expected traffic generated by FDCAN1 is:
 *
 *   ID           : 0x100 (standard)
 *   Format       : CAN FD with bit-rate switching
 *   Nominal rate : 1 Mbit/s
 *   Data rate    : 5 Mbit/s
 *   Payload      : 64 bytes (DLC code 15)
 *   data[0..3]   : monotonically increasing little-endian counter
 *   data[4..63]  : (counter + byte index) & 0xFF
 *
 * No printf is performed in the RX hot path.  Only counters and the most
 * recent mismatch are retained and printed in the once-per-second report.
 */
static uint8_t can_rx_have_counter = 0U;
static uint32_t can_rx_expected_counter = 0U;
static uint32_t can_rx_first_counter = 0U;
static uint32_t can_rx_last_counter = 0U;

static uint32_t can_rx_sequence_errors = 0U;
static uint32_t can_rx_forward_gap_frames = 0U;
static uint32_t can_rx_backward_events = 0U;
static uint32_t can_rx_id_errors = 0U;
static uint32_t can_rx_dlc_errors = 0U;
static uint32_t can_rx_header_errors = 0U;
static uint32_t can_rx_payload_errors = 0U;
static uint32_t can_rx_fifo_lost_events = 0U;
static uint32_t can_rx_max_fifo_fill = 0U;

static uint32_t can_rx_last_bad_expected = 0U;
static uint32_t can_rx_last_bad_counter = 0U;
static uint32_t can_rx_last_bad_id = 0U;
static uint32_t can_rx_last_bad_dlc = 0U;
static uint8_t can_rx_last_bad_data[64] = {0U};
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);
static void MPU_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_FDCAN1_Init(void);
static void MX_FDCAN2_Init(void);
static void MX_USART1_UART_Init(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MPU Configuration--------------------------------------------------------*/
  MPU_Config();

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* Configure the peripherals common clocks */
  PeriphCommonClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_FDCAN1_Init();
  MX_FDCAN2_Init();
  MX_USART1_UART_Init();
  /* USER CODE BEGIN 2 */
  const char msg[] =
      "\r\n"
      "================================\r\n"
      " CAN FD traffic generator\r\n"
      "================================\r\n"
      "Boot OK\r\n"
      "CPU          : 400 MHz\r\n"
      "CAN nominal  : 1 Mbit/s\r\n"
      "CAN data     : 5 Mbit/s\r\n"
      "Format       : CAN FD + BRS\r\n"
      "Pattern      : ID=100 PAYLOAD=64 counter + deterministic pattern\r\n"
      "CAN2         : independent FD RX validator enabled\r\n"
      "\r\n";

  HAL_UART_Transmit(&huart1,
                    (uint8_t *)msg,
                    sizeof(msg) - 1,
                    HAL_MAX_DELAY);

  FDCAN_TxHeaderTypeDef txHeader = {0};

  /* CAN2 accepts all non-matching standard/extended frames into FIFO0 */
  if (HAL_FDCAN_ConfigGlobalFilter(&hfdcan2,
                                   FDCAN_ACCEPT_IN_RX_FIFO0,
                                   FDCAN_ACCEPT_IN_RX_FIFO0,
                                   FDCAN_REJECT_REMOTE,
                                   FDCAN_REJECT_REMOTE) != HAL_OK)
  {
      Error_Handler();
  }

  /*
   * Start receiver first.
   * CAN2 must be active before CAN1 starts transmitting,
   * because CAN2 provides the ACK.
   */
  if (HAL_FDCAN_Start(&hfdcan2) != HAL_OK)
  {
      Error_Handler();
  }

  if (HAL_FDCAN_Start(&hfdcan1) != HAL_OK)
  {
      Error_Handler();
  }

  txHeader.Identifier = 0x100;
  txHeader.IdType = FDCAN_STANDARD_ID;
  txHeader.TxFrameType = FDCAN_DATA_FRAME;
  txHeader.DataLength = FDCAN_DLC_BYTES_64;
  txHeader.ErrorStateIndicator = FDCAN_ESI_ACTIVE;
  txHeader.BitRateSwitch = FDCAN_BRS_ON;
  txHeader.FDFormat = FDCAN_FD_CAN;
  txHeader.TxEventFifoControl = FDCAN_NO_TX_EVENTS;
  txHeader.MessageMarker = 0;

  const char can_msg[] = "FDCAN1/FDCAN2 FD+BRS started\r\n";
  HAL_UART_Transmit(&huart1,
                    (uint8_t *)can_msg,
                    sizeof(can_msg) - 1,
                    HAL_MAX_DELAY);

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */

      uint32_t now = HAL_GetTick();

      while (HAL_FDCAN_GetTxFifoFreeLevel(&hfdcan1) > 0)
      {
          uint8_t txData[64];

          txData[0] = (uint8_t)(can_tx_count);
          txData[1] = (uint8_t)(can_tx_count >> 8);
          txData[2] = (uint8_t)(can_tx_count >> 16);
          txData[3] = (uint8_t)(can_tx_count >> 24);

          for (uint32_t i = 4U; i < 64U; i++)
          {
              txData[i] = (uint8_t)(can_tx_count + i);
          }

          if (HAL_FDCAN_AddMessageToTxFifoQ(&hfdcan1,
                                            &txHeader,
                                            txData) == HAL_OK)
          {
              can_tx_count++;
          }
          else
          {
              can_tx_error++;
              break;
          }
      }

      /*
       * Observe FIFO pressure before draining it.  This allows a sequence gap
       * at CAN2 to be distinguished from a generator-side FIFO overflow.
       */
      uint32_t rx_fill =
          HAL_FDCAN_GetRxFifoFillLevel(&hfdcan2, FDCAN_RX_FIFO0);

      if (rx_fill > can_rx_max_fifo_fill)
      {
          can_rx_max_fifo_fill = rx_fill;
      }

      if (__HAL_FDCAN_GET_FLAG(&hfdcan2,
                               FDCAN_FLAG_RX_FIFO0_MESSAGE_LOST))
      {
          can_rx_fifo_lost_events++;
          __HAL_FDCAN_CLEAR_FLAG(&hfdcan2,
                                 FDCAN_FLAG_RX_FIFO0_MESSAGE_LOST);
      }

      /* Drain and validate everything received by CAN2. */
      while (HAL_FDCAN_GetRxFifoFillLevel(&hfdcan2,
                                          FDCAN_RX_FIFO0) > 0)
      {
          FDCAN_RxHeaderTypeDef rxHeader;
          uint8_t rxData[64] = {0U};

          if (HAL_FDCAN_GetRxMessage(&hfdcan2,
                                     FDCAN_RX_FIFO0,
                                     &rxHeader,
                                     rxData) == HAL_OK)
          {
              uint32_t counter =
                    ((uint32_t)rxData[0])
                  | ((uint32_t)rxData[1] << 8)
                  | ((uint32_t)rxData[2] << 16)
                  | ((uint32_t)rxData[3] << 24);

              uint32_t expected_before = counter;
              uint8_t bad = 0U;

              can_rx_count++;

              if (can_rx_have_counter == 0U)
              {
                  can_rx_have_counter = 1U;
                  can_rx_first_counter = counter;
                  can_rx_expected_counter = counter;
              }

              expected_before = can_rx_expected_counter;

              if (counter != expected_before)
              {
                  can_rx_sequence_errors++;
                  bad = 1U;

                  if (counter > expected_before)
                  {
                      can_rx_forward_gap_frames +=
                          counter - expected_before;
                  }
                  else
                  {
                      can_rx_backward_events++;
                  }

                  /* Resynchronise so one event produces one sequence error. */
                  can_rx_expected_counter = counter;
              }

              can_rx_expected_counter++;
              can_rx_last_counter = counter;

              if ((rxHeader.Identifier != 0x100U) ||
                  (rxHeader.IdType != FDCAN_STANDARD_ID))
              {
                  can_rx_id_errors++;
                  bad = 1U;
              }

              if (rxHeader.DataLength != FDCAN_DLC_BYTES_64)
              {
                  can_rx_dlc_errors++;
                  bad = 1U;
              }

              if ((rxHeader.RxFrameType != FDCAN_DATA_FRAME) ||
                  (rxHeader.FDFormat != FDCAN_FD_CAN) ||
                  (rxHeader.BitRateSwitch != FDCAN_BRS_ON))
              {
                  can_rx_header_errors++;
                  bad = 1U;
              }

              for (uint32_t i = 4U; i < 64U; i++)
              {
                  if (rxData[i] != (uint8_t)(counter + i))
                  {
                      can_rx_payload_errors++;
                      bad = 1U;
                      break;
                  }
              }

              if (bad != 0U)
              {
                  can_rx_last_bad_expected = expected_before;
                  can_rx_last_bad_counter = counter;
                  can_rx_last_bad_id = rxHeader.Identifier;
                  can_rx_last_bad_dlc = rxHeader.DataLength;

                  for (uint32_t i = 0U; i < 64U; i++)
                  {
                      can_rx_last_bad_data[i] = rxData[i];
                  }
              }
          }
      }

      /* Print status once per second. */
      if ((now - last_report_tick) >= 1000)
      {
          last_report_tick = now;

          FDCAN_ProtocolStatusTypeDef ps1 = {0};
          FDCAN_ProtocolStatusTypeDef ps2 = {0};

          FDCAN_ErrorCountersTypeDef ec1 = {0};
          FDCAN_ErrorCountersTypeDef ec2 = {0};

          HAL_FDCAN_GetProtocolStatus(&hfdcan1, &ps1);
          HAL_FDCAN_GetProtocolStatus(&hfdcan2, &ps2);

          HAL_FDCAN_GetErrorCounters(&hfdcan1, &ec1);
          HAL_FDCAN_GetErrorCounters(&hfdcan2, &ec2);

          uint32_t txFree =
              HAL_FDCAN_GetTxFifoFreeLevel(&hfdcan1);

          uint32_t rxFill =
              HAL_FDCAN_GetRxFifoFillLevel(&hfdcan2, FDCAN_RX_FIFO0);

          char status_msg[320];

          int status_len = snprintf(
              status_msg,
              sizeof(status_msg),
              "TXQ=%lu RX=%lu ADDERR=%lu free=%lu rxFill=%lu "
              "| C1 TEC=%lu REC=%lu EP=%lu BO=%lu LEC=%lu "
              "| C2 TEC=%lu REC=%lu EP=%lu BO=%lu LEC=%lu\r\n",
              (unsigned long)can_tx_count,
              (unsigned long)can_rx_count,
              (unsigned long)can_tx_error,
              (unsigned long)txFree,
              (unsigned long)rxFill,

              (unsigned long)ec1.TxErrorCnt,
              (unsigned long)ec1.RxErrorCnt,
              (unsigned long)ps1.ErrorPassive,
              (unsigned long)ps1.BusOff,
              (unsigned long)ps1.LastErrorCode,

              (unsigned long)ec2.TxErrorCnt,
              (unsigned long)ec2.RxErrorCnt,
              (unsigned long)ps2.ErrorPassive,
              (unsigned long)ps2.BusOff,
              (unsigned long)ps2.LastErrorCode);

          HAL_UART_Transmit(&huart1,
                            (uint8_t *)status_msg,
                            status_len,
                            HAL_MAX_DELAY);

          char check_msg[320];

          int check_len = snprintf(
              check_msg,
              sizeof(check_msg),
              "GENCHK first=%lu last=%lu seqErr=%lu gap=%lu back=%lu "
              "idErr=%lu dlcErr=%lu hdrErr=%lu payErr=%lu "
              "fifoLost=%lu maxFIFO=%lu\r\n",
              (unsigned long)can_rx_first_counter,
              (unsigned long)can_rx_last_counter,
              (unsigned long)can_rx_sequence_errors,
              (unsigned long)can_rx_forward_gap_frames,
              (unsigned long)can_rx_backward_events,
              (unsigned long)can_rx_id_errors,
              (unsigned long)can_rx_dlc_errors,
              (unsigned long)can_rx_header_errors,
              (unsigned long)can_rx_payload_errors,
              (unsigned long)can_rx_fifo_lost_events,
              (unsigned long)can_rx_max_fifo_fill);

          HAL_UART_Transmit(&huart1,
                            (uint8_t *)check_msg,
                            check_len,
                            HAL_MAX_DELAY);

          if ((can_rx_sequence_errors != 0U) ||
              (can_rx_id_errors != 0U) ||
              (can_rx_dlc_errors != 0U) ||
              (can_rx_header_errors != 0U) ||
              (can_rx_payload_errors != 0U))
          {
              char detail_msg[320];

              int detail_len = snprintf(
                  detail_msg,
                  sizeof(detail_msg),
                  "GENBAD exp=%lu got=%lu ID=%03lX DLCcode=%lu "
                  "DATA=%02X %02X %02X %02X %02X %02X %02X %02X\r\n",
                  (unsigned long)can_rx_last_bad_expected,
                  (unsigned long)can_rx_last_bad_counter,
                  (unsigned long)can_rx_last_bad_id,
                  (unsigned long)can_rx_last_bad_dlc,
                  can_rx_last_bad_data[0], can_rx_last_bad_data[1],
                  can_rx_last_bad_data[2], can_rx_last_bad_data[3],
                  can_rx_last_bad_data[4], can_rx_last_bad_data[5],
                  can_rx_last_bad_data[6], can_rx_last_bad_data[7]);

              HAL_UART_Transmit(&huart1,
                                (uint8_t *)detail_msg,
                                detail_len,
                                HAL_MAX_DELAY);
          }
      }
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Supply configuration update enable
  */
  HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);

  /** Configure the main internal regulator output voltage
  */
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

  while(!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) {}

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 1;
  RCC_OscInitStruct.PLL.PLLN = 100;
  RCC_OscInitStruct.PLL.PLLP = 2;
  RCC_OscInitStruct.PLL.PLLQ = 3;
  RCC_OscInitStruct.PLL.PLLR = 2;
  RCC_OscInitStruct.PLL.PLLRGE = RCC_PLL1VCIRANGE_3;
  RCC_OscInitStruct.PLL.PLLVCOSEL = RCC_PLL1VCOWIDE;
  RCC_OscInitStruct.PLL.PLLFRACN = 0;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2
                              |RCC_CLOCKTYPE_D3PCLK1|RCC_CLOCKTYPE_D1PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.SYSCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB3CLKDivider = RCC_APB3_DIV2;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_APB1_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_APB2_DIV2;
  RCC_ClkInitStruct.APB4CLKDivider = RCC_APB4_DIV2;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief Peripherals Common Clock Configuration
  * @retval None
  */
void PeriphCommonClock_Config(void)
{
  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};

  /** Initializes the peripherals clock
  */
  PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_FDCAN;
  PeriphClkInitStruct.PLL2.PLL2M = 1;
  PeriphClkInitStruct.PLL2.PLL2N = 20;
  PeriphClkInitStruct.PLL2.PLL2P = 2;
  PeriphClkInitStruct.PLL2.PLL2Q = 2;
  PeriphClkInitStruct.PLL2.PLL2R = 2;
  PeriphClkInitStruct.PLL2.PLL2RGE = RCC_PLL2VCIRANGE_3;
  PeriphClkInitStruct.PLL2.PLL2VCOSEL = RCC_PLL2VCOMEDIUM;
  PeriphClkInitStruct.PLL2.PLL2FRACN = 0;
  PeriphClkInitStruct.FdcanClockSelection = RCC_FDCANCLKSOURCE_PLL2;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief FDCAN1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_FDCAN1_Init(void)
{

  /* USER CODE BEGIN FDCAN1_Init 0 */

  /* USER CODE END FDCAN1_Init 0 */

  /* USER CODE BEGIN FDCAN1_Init 1 */

  /* USER CODE END FDCAN1_Init 1 */
  hfdcan1.Instance = FDCAN1;
  hfdcan1.Init.FrameFormat = FDCAN_FRAME_FD_BRS;
  hfdcan1.Init.Mode = FDCAN_MODE_NORMAL;
  hfdcan1.Init.AutoRetransmission = ENABLE;
  hfdcan1.Init.TransmitPause = DISABLE;
  hfdcan1.Init.ProtocolException = DISABLE;
  hfdcan1.Init.NominalPrescaler = 5;
  hfdcan1.Init.NominalSyncJumpWidth = 2;
  hfdcan1.Init.NominalTimeSeg1 = 13;
  hfdcan1.Init.NominalTimeSeg2 = 2;
  hfdcan1.Init.DataPrescaler = 1;
  hfdcan1.Init.DataSyncJumpWidth = 3;
  hfdcan1.Init.DataTimeSeg1 = 12;
  hfdcan1.Init.DataTimeSeg2 = 3;
  hfdcan1.Init.MessageRAMOffset = 0;
  hfdcan1.Init.StdFiltersNbr = 0;
  hfdcan1.Init.ExtFiltersNbr = 0;
  hfdcan1.Init.RxFifo0ElmtsNbr = 0;
  hfdcan1.Init.RxFifo0ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan1.Init.RxFifo1ElmtsNbr = 0;
  hfdcan1.Init.RxFifo1ElmtSize = FDCAN_DATA_BYTES_8;
  hfdcan1.Init.RxBuffersNbr = 0;
  hfdcan1.Init.RxBufferSize = FDCAN_DATA_BYTES_8;
  hfdcan1.Init.TxEventsNbr = 0;
  hfdcan1.Init.TxBuffersNbr = 0;
  hfdcan1.Init.TxFifoQueueElmtsNbr = 32;
  hfdcan1.Init.TxFifoQueueMode = FDCAN_TX_FIFO_OPERATION;
  hfdcan1.Init.TxElmtSize = FDCAN_DATA_BYTES_64;
  if (HAL_FDCAN_Init(&hfdcan1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN FDCAN1_Init 2 */

  /* USER CODE END FDCAN1_Init 2 */

}

/**
  * @brief FDCAN2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_FDCAN2_Init(void)
{

  /* USER CODE BEGIN FDCAN2_Init 0 */

  /* USER CODE END FDCAN2_Init 0 */

  /* USER CODE BEGIN FDCAN2_Init 1 */

  /* USER CODE END FDCAN2_Init 1 */
  hfdcan2.Instance = FDCAN2;
  hfdcan2.Init.FrameFormat = FDCAN_FRAME_FD_BRS;
  hfdcan2.Init.Mode = FDCAN_MODE_NORMAL;
  hfdcan2.Init.AutoRetransmission = DISABLE;
  hfdcan2.Init.TransmitPause = DISABLE;
  hfdcan2.Init.ProtocolException = DISABLE;
  hfdcan2.Init.NominalPrescaler = 5;
  hfdcan2.Init.NominalSyncJumpWidth = 2;
  hfdcan2.Init.NominalTimeSeg1 = 13;
  hfdcan2.Init.NominalTimeSeg2 = 2;
  hfdcan2.Init.DataPrescaler = 1;
  hfdcan2.Init.DataSyncJumpWidth = 3;
  hfdcan2.Init.DataTimeSeg1 = 12;
  hfdcan2.Init.DataTimeSeg2 = 3;
  hfdcan2.Init.MessageRAMOffset = 576;
  hfdcan2.Init.StdFiltersNbr = 0;
  hfdcan2.Init.ExtFiltersNbr = 0;
  hfdcan2.Init.RxFifo0ElmtsNbr = 32;
  hfdcan2.Init.RxFifo0ElmtSize = FDCAN_DATA_BYTES_64;
  hfdcan2.Init.RxFifo1ElmtsNbr = 0;
  hfdcan2.Init.RxFifo1ElmtSize = FDCAN_DATA_BYTES_64;
  hfdcan2.Init.RxBuffersNbr = 0;
  hfdcan2.Init.RxBufferSize = FDCAN_DATA_BYTES_64;
  hfdcan2.Init.TxEventsNbr = 0;
  hfdcan2.Init.TxBuffersNbr = 0;
  hfdcan2.Init.TxFifoQueueElmtsNbr = 0;
  hfdcan2.Init.TxFifoQueueMode = FDCAN_TX_FIFO_OPERATION;
  hfdcan2.Init.TxElmtSize = FDCAN_DATA_BYTES_8;
  if (HAL_FDCAN_Init(&hfdcan2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN FDCAN2_Init 2 */

  /* USER CODE END FDCAN2_Init 2 */

}

/**
  * @brief USART1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART1_UART_Init(void)
{

  /* USER CODE BEGIN USART1_Init 0 */

  /* USER CODE END USART1_Init 0 */

  /* USER CODE BEGIN USART1_Init 1 */

  /* USER CODE END USART1_Init 1 */
  huart1.Instance = USART1;
  huart1.Init.BaudRate = 115200;
  huart1.Init.WordLength = UART_WORDLENGTH_8B;
  huart1.Init.StopBits = UART_STOPBITS_1;
  huart1.Init.Parity = UART_PARITY_NONE;
  huart1.Init.Mode = UART_MODE_TX_RX;
  huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart1.Init.OverSampling = UART_OVERSAMPLING_16;
  huart1.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
  huart1.Init.ClockPrescaler = UART_PRESCALER_DIV1;
  huart1.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
  if (HAL_UART_Init(&huart1) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_SetTxFifoThreshold(&huart1, UART_TXFIFO_THRESHOLD_1_8) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_SetRxFifoThreshold(&huart1, UART_RXFIFO_THRESHOLD_1_8) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_DisableFifoMode(&huart1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART1_Init 2 */

  /* USER CODE END USART1_Init 2 */

}

/**
  * Enable DMA controller clock
  */
static void MX_DMA_Init(void)
{

  /* DMA controller clock enable */
  __HAL_RCC_DMA1_CLK_ENABLE();

  /* DMA interrupt init */
  /* DMA1_Stream0_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Stream0_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(DMA1_Stream0_IRQn);

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOA, CAN1_STBM_Pin|CAN2_STBM_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pins : CAN1_STBM_Pin CAN2_STBM_Pin */
  GPIO_InitStruct.Pin = CAN1_STBM_Pin|CAN2_STBM_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

 /* MPU Configuration */

void MPU_Config(void)
{
  MPU_Region_InitTypeDef MPU_InitStruct = {0};

  /* Disables the MPU */
  HAL_MPU_Disable();

  /** Initializes and configures the Region and the memory to be protected
  */
  MPU_InitStruct.Enable = MPU_REGION_ENABLE;
  MPU_InitStruct.Number = MPU_REGION_NUMBER0;
  MPU_InitStruct.BaseAddress = 0x0;
  MPU_InitStruct.Size = MPU_REGION_SIZE_4GB;
  MPU_InitStruct.SubRegionDisable = 0x87;
  MPU_InitStruct.TypeExtField = MPU_TEX_LEVEL0;
  MPU_InitStruct.AccessPermission = MPU_REGION_NO_ACCESS;
  MPU_InitStruct.DisableExec = MPU_INSTRUCTION_ACCESS_DISABLE;
  MPU_InitStruct.IsShareable = MPU_ACCESS_SHAREABLE;
  MPU_InitStruct.IsCacheable = MPU_ACCESS_NOT_CACHEABLE;
  MPU_InitStruct.IsBufferable = MPU_ACCESS_NOT_BUFFERABLE;

  HAL_MPU_ConfigRegion(&MPU_InitStruct);
  /* Enables the MPU */
  HAL_MPU_Enable(MPU_PRIVILEGED_DEFAULT);

}

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file name
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */